### ISSUE TITLE
command "thrift" misspelled or not found

### ISSUE THREAD

**Issue by Braindea7** [amrelnaggar/laravel-thrift#1]
Hey,

I have a problem with php artisan.
If I try to execute `php artisan thrift:compile mythrift.thrift "App\\\Thrift\\\MyThrift`
, I get the error "command "thrift" is misspelled or not found". I think I've found the error in the CompileCommand.php file. The standardpath inside the handle() function is "thrift", but this seems to be wrong.. I'am new to Laravel, so I have no clue which path this means. 

I install your laravel-thrift as recommended: required, register Serviceprovider and register Focade, publish Serviceprovider.

Greetings from Germany.

EDIT: I'am sorry! I found the problem. In Windows I don't have a global thrift command. You need to download the thrift.exe file from the apache website and either copy it in your laravel project folder and change the standardpath in your Command php files or execute the artisan commands with the --path attribute to your thrift.exe

**Comment by amrelnaggar** [comment]
Glad to hear that you were able to fix it. 

The `--path` option is the way to go, since any changes to the package files would be removed if you ran `composer install` after deploying your app on a server.
